### ISSUE TITLE
ステートメントで第三者にコミットを求めるべきか否か

### ISSUE THREAD

**Issue by kotobuki** [statement-for-nft-art/statement#2]
ステートメントの草稿では、最後の部分において以下のように第三者にコミットを求めています。

https://github.com/statement-for-nft-art/statement/blob/91f3b88c295c8bc7cd0bced848606073a4cff887/statement.md?plain=1#L17-L20
> また、私たちの〈NFTアート〉に関わる全ての人々に、以下のことを求めます。
> 
> オーナーシップに伴う権利だけでなく責任を理解する
> 剽窃や盗用をしない

剽窃や盗用による作品が残り続けてしまう〈NFT〉アートに関わるのであれば、それに伴う責任を明確に理解することを第三者にも求めるのは妥当なのではという考え方が一方にあります。他方で、このように第三者に何かを求めることは、Web3の文化的ではないのではという意見もあります。

ステートメントの最終版においてこの部分をそのまま残すべき、修正して残すべき、削除すべき、などこの論点に関するコメントがあればお願いします。

**Comment by j-nakada** [comment]
第3者にコミットを求めるべきか否かの意見とはズレてしまうかもしれませんが、この文面だけではどこからが剽窃や盗用にあたるのかの線引きが曖昧との印象を持ちました

あるNFT作品から影響を受けて作成された別のNFTが、どの程度まで似通っていたらアウトなのかは当事者間の関係性やコミュニティの寛容さによって様々な線引きが存在する可能性があります
例えばオリジナルのあからさまな加工コピーNFTでもある種のパロディとして受け入れられる文化もありえるでしょうし、別の場所では同程度の加工でも厳しく批判されることもあり得るかもしれません

関係者全てに求める内容として線引きが曖昧になりそうなものは含めないほうが良いかと思いますがどうでしょうか
剽窃や盗用の部分は個々のNFTの適用ライセンスの範疇として切り離しても良いと思います

**Comment by kotobuki** [comment]
2022年1月12日に開催した「`#NFTアートのステートメント`を考え始めてみようという会：第3回」での議論を経て、以下のように整理したいと思います。

> ステートメントで第三者へのコミットは求めない。まず、第1項の「オーナーシップに伴う権利だけでなく責任を理解する」は、オーナーシップに責任まで伴うという社会的コンセンサスが醸成されていないため、一義的に解釈できない。次に、第2項の「剽窃や盗用をしない」は、法律に反しないというレベルの話であり、法律を守ることについては既に社会的コンセンサスが得られている。さらに、「私たちの〈NFTアート〉に関わる全ての人々に、以下のことを求めます。」はかなり強い表現であり、ステートメントへの賛同を得にくくなることが懸念される。以上の理由により、第三者にコミットを求める部分は削除する。
