### ISSUE TITLE
「コミュニティ」に代わる表現

### ISSUE THREAD

**Issue by kotobuki** [statement-for-nft-art/statement#3]
ステートメントの草稿では、次のように記載しています。

https://github.com/statement-for-nft-art/statement/blob/91f3b88c295c8bc7cd0bced848606073a4cff887/statement.md?plain=1#L14
> コミュニティと誠実に向き合う

ここで、10,000点など多くの作品を同時に扱うことが一般的なジェネラティブアートのような場合には、「コミュニティ」という表現は妥当だと思われます。しかしながら、作品数が少ない場合には1:1の関係になるため、「コミュニティ」という表現は不適当だと考えられます。また、作品数が10,000点の場合であっても、NFTを購入した人との関係でいえば、1:1:10,000の様な関係になります。

こうした関係を丁寧に扱うため、「コミュニティ」に代わる表現を探したいと思います。何か提案があればお寄せください。

**Comment by wildmouse** [comment]
コレクター、ホルダー、サポーターが別の選択肢に挙げられると思います。

- コレクター(Collectors): NFTを収集している人。複数のNFTを集めているという意味合いが強い。
- ホルダー(Holders): NFTを所有している人全般。コレクターが複数個のNFTを保有しているのに対して単に保有している状態を指し、1つのNFTアートを保有している場合でも適用できるように見受けられる。
- サポーター(Supporters): NFTアート、あるいはNFTのアーティストをサポートする人。NFTを保有していない人でも当てはまる。

コレクター、ホルダーの場合直接的にNFTを購入あるいは保有しているという意味で関係性が明確ですが、保有者に限定されるように思います。

またサポーターという言葉はアーティストを「支持する」という側面が強いのに対し、コミュニティという言葉は参加者同士がアーティストや他の立場関係なく同等かつ相互的にやりとりをしているように感じます。
主従的な関係を含む場合はサポーターそれがない場合はコミュニティ、という形で区別はできそうです。

**Comment by j-nakada** [comment]
確かにNFT作品ごとに想定される関係は様々なので「誠実に向き合う対象」としては複数併記しても良いのではないかと思いました。

コミュニティ/ホルダー/サポーターと誠実に向き合う

**Comment by kotobuki** [comment]
2022年1月12日に開催した「`#NFTアートのステートメント`を考え始めてみようという会：第3回」での議論を経て、以下のように整理したいと思います。

> コミュニティよりももう少し広い、例えば「ステークホルダー」のような言葉に置き換え、アーティスト、クリエイター、コレクター、ホルダー、サポーターなど関与するアクターを例示する。これにより、〈NFT〉アートに関わる人々の具体像を提示できる。なお、ステートメントはあくまでNFTを発行する側の立場で書きつつ、それ以外の立場の人々も賛同を示せるよう、2つの部分に分ける。
